name: Main

on:
  push:
    branches:
      - '*'
jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Cache Go Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: ./build.sh

      - name: Run Tests
        env:
          AUTOGRADER__DOCKER__DISABLE: 'true'
        run: ./test.sh
