name: Main

on:
  push:
    branches:
      - '*'
jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('_tests/requirements.txt') }}

      - name: Install Python Dependencies
        run: pip3 install -U -r _tests/requirements.txt

      - name: Build
        run: ./build.sh

      - name: Run Base Tests
        env:
          AUTOGRADER__DOCKER__DISABLE: 'true'
        run: ./test.sh

      - name: Run Submission Tests
        env:
          AUTOGRADER__DOCKER__DISABLE: 'true'
        run: |
            echo "TEST - Run Remote tests once Python interface is updated for v2."
            echo ./.ci/run_remote_tests.sh

      - name: Verify Python Interface Test Data
        env:
          AUTOGRADER__DOCKER__DISABLE: 'true'
        run: |
            ./.ci/verify-py-test-data.sh
